### ISSUE TITLE
Challenge snippets containing [tab] characters are difficult to type

### ISSUE THREAD

**Issue by JSn1nj4** [codicocodes/speedtyper-community#3]
In SpeedTyper, pressing `[tab]` moves my focus out of the typing area. Tabs and spaces also look like plain white space depending on any other characters preceding them, so there may not be an easy way to tell there's a tab in the code snippet.

One example I came across today was from this [autophytes/jotling file][jotling_src_file] (loosely referenced in the [related challenges file][jotling_challenges]).

I kept seeing a commented-out section of code with what I thought was a space, but I only realized it was a tab after several tries to enter a space or the text right after it (`if`). Only issue is I had to use a special key combination to insert the tab. In my case, I used Windows' `[alt]+numpad 0191`.

I'm sorry, I didn't think to grab a screenshot of the issue before I closed the tab...

Here's what I'm using:
- Brave 1.23.75 Chromium: 90.0.4430.93
- Windows 10 Home, version 2004, build 19041.928, experience pack 120.2212.551.0
  (I'm not sure the build or experience pack numbers matter honestly, but they're there just in case)

[jotling_src_file]: https://github.com/autophytes/jotling/blob/master/src/contexts/findReplaceContext.js
[jotling_challenges]: https://github.com/codicocodes/speedtyper-community/blob/main/challenges/jotling.js#L5

**Comment by JSn1nj4** [comment]
I'm considering jumping in on this to help out a little bit if you're open to PRs @codicocodes. I was thinking about this the other day and I would think the best solution would involve something like these:
- Render invisible characters
- Intercept `[tab]` when pressed in the typing box

Of course I'm saying this without knowing immediately what would be involved for the first part. This depends on how the code editor emulator is implemented or what package is used for this, right?

**Comment by the-gremlin** [comment]
im gonna bump this as it is a big problem in the C snippets as all of them require pressing Tab

**Comment by codicocodes** [comment]
Hi thanks for making the issue!

Tabs are now parsed into two spaces and treated as regular indentation
which does not have to be typed. The c challenges seem to be working
correctly. (Inline indentation has to be typed)

tors 3 juni 2021 kl. 18:09 skrev the-gremlin ***@***.***>:
